#!/bin/bash

# Override the image name used for local development
IMAGE_NAME=${CLOUD_WORKSTATION_IMAGE:-joshmahowald/cloud-workstation}

if [[ $1 == '--update' ]]; then
    echo "updating underlying image"
    docker pull $IMAGE_NAME
    exit 0
fi


docker run -it --rm \
    -v $(pwd):/workspace \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
    -v ~/.ssh/known_hosts:/root/.ssh/known_hosts \
    -e DIRENV_ALLOW=$DIRENV_ALLOW \
    -e AWS_ROLE_NAME=$AWS_ROLE_NAME \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e CUR_DIR_NAME=$(basename $PWD) \
    $IMAGE_NAME $@
